name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      projects:
        description: 'Projects name separated by ,'
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Split projects name
        id: split_projects
        run: |
          PROJECTS="$( echo ${{ github.event.inputs.projects }} | sed 's/,/\n/g')"
          PROJECTS="${PROJECTS//'%'/'%25'}"
          PROJECTS="${PROJECTS//$'\n'/'%0A'}"
          PROJECTS="${PROJECTS//$'\r'/'%0D'}"
          echo "::set-output name=projects::$PROJECTS"

      - name: Display
        run: echo ${{ matrix.project }}
        strategy:
          matrix:
            project: ${{ steps.split_projects.outputs.projects }}