name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      projects:
        description: 'Projects name separated by ,'
        required: true

jobs:
  define_project:
    runs-on: ubuntu-latest
    outputs:
      projects: ${{ steps.create_array.outputs.projects }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install py
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Build array of projects
        id: split_projects
        run: |
          INPUT_VAL="${{ github.event.inputs.projects }}"
          PROJECT_ARRAY="$(python parse.py \"$INPUT_VAL\")"
          echo "PROJECT_ARRAY=$PROJECT_ARRAY"
          echo "PROJECT_ARRAY=$PROJECT_ARRAY" >> $GITHUB_ENV
#          echo "PROJECT_ARRAY<<EOF" >> $GITHUB_ENV
#          echo "$PROJECT_ARRAY" >> $GITHUB_ENV
#          echo "EOF" >> $GITHUB_ENV

      - name: Create array
        id: create_array
        run: |
          echo "::set-output name=projects::${{ toJSON(env.PROJECT_ARRAY) }}"

  show_projects:
    needs: define_project
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: ${{ fromJSON(needs.define_project.outputs.projects) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Display
        run: |
          echo ${{ matrix.project }}
      - name: Build project
        run: ./gradlew :${{ matrix.project }}:build
