name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      projects:
        description: 'Projects name separated by ,'
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Split projects name
        id: split_projects
        run: |
          TEST_V=$( echo test1,test2 | sed 's/,/\n/g')
          echo '::set-output name=projects::$TEST_V'

      - name: Display
        run: echo ${{ steps.split_projects.output.projects }}