name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      projects:
        description: 'Projects name separated by ,'
        required: true

jobs:
  define_project:
    runs-on: ubuntu-latest
    outputs:
      projects: ${{ steps.split_projects.outputs.projects }}
    steps:
      - name: Split projects name
        id: split_projects
        run: |
          PROJECTS="$( echo ${{ github.event.inputs.projects }} | sed 's/,/\n/g')"
          PROJECTS="${PROJECTS//'%'/'%25'}"
          PROJECTS="${PROJECTS//$'\n'/'%0A'}"
          PROJECTS="${PROJECTS//$'\r'/'%0D'}"
          echo "::set-output name=projects::$PROJECTS"

  show_projects:
    needs: define_project
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: ${{ needs.define_project.outputs.projects }}
    steps:
      - name: Display
        run: echo ${{ matrix.project }}